import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import iconNotification from "../public/iconNotification.png";
import Home from "../public/Home.png"
import star from "../public/star.png"
import Message from "../public/Message.png"
import User from "../public/User.png"

import {Manrope} from "next/font/google";
const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });



export const metadata: Metadata = {
  title: "Family Firends",
  description: "Generated by Julie",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable}antialiased`}
        
      >
        <nav className="sticky top-0 bg-[var(--background)] z-50 ">
          <div className="mx-4 flex justify-between p-4">
          <div className="font-bold text-2xl not-italic">
            <h1>FamilyFriends</h1>
          </div>
          <div>
          <Image
  src={iconNotification}      
  alt="iconNotification" 
  width={25} 
  height={25}
 />
 </div>
          </div>
        </nav>
        <section>

        </section>
        {children}

        <footer className="fixed bottom-0 left-0 w-full bg-[var(--background)] z-50 shadow-t">
          <div className="mx-4 flex justify-evenly p-4">
          <Image
  src={Home}      
  alt="home" 
  width={25} 
  height={25}
 />
 <Image
  src={star}      
  alt="iconNotification" 
  width={25} 
  height={25}
 /><Image
 src={Message}      
 alt="iconNotification" 
 width={25} 
 height={25}
/><Image
  src={User}      
  alt="iconNotification" 
  width={25} 
  height={25}
 />
          </div>

        </footer>
      </body>
    </html>
  );
}
